theme: jekyll-theme-minimal
title: AhoY S03!
description: This is an experimental project.
name: khns
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
  future: true
  jailed: false
  gfm_quirks: paragraph_end
plugins:
  - jemoji